// src/components/DetailPanel.jsx
import { formatDate, formatWon } from '../lib/notices';

function Row({ label, children }) {
  return (
    <div className="facts__row">
      <dt>{label}</dt>
      <dd>{children}</dd>
    </div>
  );
}

function specialDetail(s) {
  const bits = [];
  if (s.requiresNoHouse) bits.push('무주택');
  if (s.minChildren) bits.push(`자녀 ${s.minChildren}명 이상`);
  if (s.maxMarriageYears) bits.push(`혼인 ${s.maxMarriageYears}년 이내`);
  if (s.incomeLimit) bits.push(`소득 ${s.incomeLimit}% 이하`);
  return bits.length ? bits.join(' · ') : '별도 소득요건 없음';
}

export default function DetailPanel({ item, onClose, onFocus }) {
  if (!item) return null;

  const pdfUrl = item.pdf ? `/공고문/${encodeURIComponent(item.pdf)}` : null;
  const specials = item.special.filter((s) => s.type !== '일반공급');
  const general = item.special.find((s) => s.type === '일반공급');

  return (
    <aside className="detail" style={{ '--accent': item.color }}>
      <header className="detail__head">
        <div>
          <div className="detail__badges">
            <span className={`badge badge--${item.status}`}>
              {item.status === 'open' ? item.label : item.status === 'closed' ? '접수마감' : '일정 확인'}
            </span>
            <span className="chip chip--solid">{item.housingType}</span>
            {item.agencyName && <span className="chip chip--ghost">{item.agencyName}</span>}
          </div>
          <h2>{item.title}</h2>
          <p className="detail__where">
            {item.address ?? `${item.region} ${item.district ?? ''}`}
            {item.approxLabel && <em className="detail__approx"> · 위치 {item.approxLabel}</em>}
          </p>
        </div>
        <button type="button" className="detail__close" onClick={onClose} aria-label="닫기">
          ×
        </button>
      </header>

      <section className="detail__price">
        <span>공급금액(공고문 기재 범위)</span>
        {item.priceMin != null ? (
          <strong>
            {formatWon(item.priceMin)} <i>~</i> {formatWon(item.priceMax)}
          </strong>
        ) : (
          <strong className="muted">공고문 참고</strong>
        )}
        <small>주택형·층·옵션에 따라 달라집니다. 정확한 금액은 원문 공고를 확인하세요.</small>
      </section>

      <dl className="facts">
        <Row label="모집공고일">{formatDate(item.announce)}</Row>
        <Row label="청약 마감">{item.deadline ? formatDate(item.deadline) : '공고문 참고'}</Row>
        <Row label="공급 유형">{item.housingType}</Row>
        <Row label="사업 주체">{item.agencyName || item.agency}</Row>
        <Row label="소재지">
          {item.address ?? '-'}
          {item.addressSource && <span className="facts__src"> ({item.addressSource})</span>}
        </Row>
        <Row label="청약통장">
          {item.minSubMonths ? `가입 ${item.minSubMonths}개월 이상` : '통장 요건 없음/공고문 참고'}
        </Row>
        <Row label="신청 연령">{item.minAge ? `만 ${item.minAge}세 이상` : '공고문 참고'}</Row>
      </dl>

      {specials.length > 0 && (
        <section className="detail__block">
          <h3>특별공급 {specials.length}종</h3>
          <ul className="specials">
            {specials.map((s) => (
              <li key={s.type}>
                <b>{s.type}</b>
                <span>{specialDetail(s)}</span>
              </li>
            ))}
          </ul>
          {general && <p className="detail__note">일반공급: {specialDetail(general)}</p>}
        </section>
      )}

      {item.extra && (
        <section className="detail__block">
          <h3>공고 요약</h3>
          <dl className="facts facts--compact">
            {Object.entries(item.extra)
              .filter(([, v]) => v && typeof v !== 'object')
              .map(([k, v]) => (
                <Row key={k} label={k.replace(/_/g, ' ')}>
                  {String(v)}
                </Row>
              ))}
          </dl>
        </section>
      )}

      {item.note && <p className="detail__note">{item.note}</p>}

      <footer className="detail__foot">
        {pdfUrl && (
          <a className="btn btn--primary" href={pdfUrl} target="_blank" rel="noreferrer">
            공고문 원문 PDF
          </a>
        )}
        {item.url && (
          <a className="btn" href={item.url} target="_blank" rel="noreferrer">
            기관 홈페이지
          </a>
        )}
        <button type="button" className="btn" onClick={() => onFocus?.(item)}>
          지도에서 보기
        </button>
      </footer>
    </aside>
  );
}

// src/components/DetailPanel.vue
<script setup>
import { computed } from 'vue';
import { formatDate, formatWon, priceLabel, statusLabelOf } from '../lib/notices';
import { communityStore } from '../stores/community';
import CommunityPanel from './CommunityPanel.vue';

const props = defineProps({
  item: { type: Object, required: true },
  match: { type: Object, default: null },
  /** 'info' | 'community' — 커뮤니티는 화면이 넓을 때만 이 패널 안에서 열린다. */
  tab: { type: String, default: 'info' },
});

const emit = defineEmits(['close', 'focus', 'select-tab', 'goto-notice']);

const pdfUrl = computed(() => (props.item.pdf ? `/공고문/${encodeURIComponent(props.item.pdf)}` : null));
const specials = computed(() => (props.item.special ?? []).filter((s) => s.type !== '일반공급'));
const general = computed(() => (props.item.special ?? []).find((s) => s.type === '일반공급'));
const postCount = computed(() => communityStore.countFor(props.item.id));
const extras = computed(() =>
  props.item.extra ? Object.entries(props.item.extra).filter(([, v]) => v && typeof v !== 'object') : []
);

function specialDetail(s) {
  const bits = [];
  if (s.requiresNoHouse) bits.push('무주택');
  if (s.minChildren) bits.push(`자녀 ${s.minChildren}명 이상`);
  if (s.maxMarriageYears) bits.push(`혼인 ${s.maxMarriageYears}년 이내`);
  if (s.incomeLimit) bits.push(`소득 ${s.incomeLimit}% 이하`);
  return bits.length ? bits.join(' · ') : '별도 소득요건 없음 (공고문 확인)';
}
</script>

<template>
  <aside class="detail" :style="{ '--accent': item.color }">
    <header class="detail__head">
      <div>
        <div class="detail__badges">
          <span class="badge" :class="`badge--${item.status}`">{{ statusLabelOf(item) }}</span>
          <span class="chip chip--solid">{{ item.housingType }}</span>
          <span v-if="item.agencyName" class="chip chip--ghost">{{ item.agencyName }}</span>
        </div>
        <h2>{{ item.title }}</h2>
        <p class="detail__where">
          {{ item.address ?? item.placeLabel }}
          <em v-if="item.approxLabel" class="detail__approx"> · 위치 {{ item.approxLabel }}</em>
        </p>
      </div>
      <button type="button" class="detail__close" aria-label="닫기" @click="emit('close')">×</button>
    </header>

    <nav class="detail__tabs" role="tablist">
      <button type="button" role="tab" :aria-selected="tab === 'info'" :class="{ 'is-on': tab === 'info' }" @click="emit('select-tab', 'info')">
        공고 정보
      </button>
      <button
        type="button"
        role="tab"
        :aria-selected="tab === 'community'"
        :class="{ 'is-on': tab === 'community' }"
        @click="emit('select-tab', 'community')"
      >
        지역 커뮤니티<i v-if="postCount">{{ postCount }}</i>
      </button>
    </nav>

    <div v-if="tab === 'info'" class="detail__body">
      <section v-if="match" class="matchbox" :class="match.ok ? 'is-ok' : 'is-no'">
        <h3>{{ match.ok ? `내 조건 — ${match.tierLabel}` : '지금 조건으로는 어려워요' }}</h3>
        <ul v-if="match.matched.length" class="matchbox__list">
          <li v-for="m in match.matched" :key="m.type" :class="{ 'is-uncertain': m.uncertain }">
            <b>{{ m.label }}</b><span>{{ m.note }}</span>
          </li>
        </ul>
        <ul v-if="match.blockers.length" class="matchbox__blockers">
          <li v-for="b in match.blockers" :key="b">{{ b }}</li>
        </ul>
        <p v-if="!match.ok && !match.blockers.length && match.missed.length" class="matchbox__miss">
          {{ match.missed[0].label }} 등 {{ match.missed.length }}개 유형이 조건에서 벗어났어요 ({{ match.missed[0].reason }})
        </p>
      </section>

      <section class="detail__price">
        <span>공급금액(공고문 기재 범위)</span>
        <strong v-if="item.priceMin != null">
          {{ formatWon(item.priceMin) }} <i>~</i> {{ formatWon(item.priceMax) }}
        </strong>
        <strong v-else class="muted">{{ priceLabel(item) }}</strong>
        <small>주택형·층·옵션에 따라 달라집니다. 정확한 금액은 원문 공고를 확인하세요.</small>
      </section>

      <dl class="facts">
        <div class="facts__row"><dt>모집공고일</dt><dd>{{ formatDate(item.announce) }}</dd></div>
        <div class="facts__row"><dt>청약 마감</dt><dd>{{ item.deadline ? formatDate(item.deadline) : '공고문 참고' }}</dd></div>
        <div class="facts__row"><dt>공급 유형</dt><dd>{{ item.housingType }}</dd></div>
        <div class="facts__row"><dt>사업 주체</dt><dd>{{ item.agencyName || item.agency }}</dd></div>
        <div class="facts__row">
          <dt>소재지</dt>
          <dd>
            {{ item.address ?? '-' }}
            <span v-if="item.addressSource" class="facts__src"> ({{ item.addressSource }})</span>
          </dd>
        </div>
        <div class="facts__row">
          <dt>청약통장</dt>
          <dd>{{ item.minSubMonths ? `가입 ${item.minSubMonths}개월 이상` : '통장 요건 없음/공고문 참고' }}</dd>
        </div>
        <div class="facts__row"><dt>신청 연령</dt><dd>{{ item.minAge ? `만 ${item.minAge}세 이상` : '공고문 참고' }}</dd></div>
      </dl>

      <section v-if="specials.length" class="detail__block">
        <h3>특별공급 {{ specials.length }}종</h3>
        <ul class="specials">
          <li v-for="s in specials" :key="s.type">
            <b>{{ s.type }}</b>
            <span>{{ specialDetail(s) }}</span>
          </li>
        </ul>
        <p v-if="general" class="detail__note">일반공급: {{ specialDetail(general) }}</p>
      </section>

      <section v-if="extras.length" class="detail__block">
        <h3>공고 요약</h3>
        <dl class="facts facts--compact">
          <div v-for="[k, v] in extras" :key="k" class="facts__row">
            <dt>{{ k.replace(/_/g, ' ') }}</dt>
            <dd>{{ v }}</dd>
          </div>
        </dl>
      </section>

      <p v-if="item.note" class="detail__note">{{ item.note }}</p>

      <footer class="detail__foot">
        <a v-if="pdfUrl" class="btn btn--primary" :href="pdfUrl" target="_blank" rel="noreferrer">공고문 원문 PDF</a>
        <a v-if="item.url" class="btn" :href="item.url" target="_blank" rel="noreferrer">기관 홈페이지</a>
        <button type="button" class="btn" @click="emit('focus', item)">지도에서 보기</button>
      </footer>
    </div>

    <div v-else class="detail__body detail__body--community">
      <CommunityPanel :notice="item" @goto-notice="emit('goto-notice', $event)" />
    </div>
  </aside>
</template>
